### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by R4wizard** [R4wizard/shadowbot-core#1]
- [x] Plugins should be dynamically loaded from a chain of sources:
  - [x] 1. a file folder on the server configured via the `dataPath` setting.
  - [x] 2. any installed node modules with a package name matching `shadowbot-plugin-*`.
  - [x] 3. built-in plugins that are stored in the `./src/Plugins` folder.
- [ ] Plugins should be able to be quickly added/removed/reloaded via a built-in interface. This interface should at the very least allow:
  - [x] listing loaded plugins and their status.
  - [x] load/unload/reloading of plugins.
  - [ ] addition and deletion of plugins by wrapping `npm`.
  - [ ] updating existing plugins by wrapping `npm`.
  - [ ] hot reloading of local plugins (inside dataPath)

**Comment by Nuxij** [comment]
I am seeing errors when trying to import socket.io or socket.io-client from within a plugin.

```
[info][Connection/IRC] initialized connection handler
[info][Connection/Facebook] initialized connection handler
[info][Connection/Facebook] connected and ready for messages
[error][Plugin/shadowbot-plugin-spotify] SyntaxError: Unexpected token .
    at Object.ex [as .js] (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/sandbox.js:53:19)
    at _require (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/sandbox.js:248:24)
    at module.exports.path (/Users/jme/Documents/shared/jme/code/shadowbot-core/plugins/shadowbot-plugin-spotify:3:21)
    at Object.Decontextify.object.host.Object.assign.apply.e [as apply] (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/contextify.js:79:36)
    at e (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/Plugin.js:83:22)
    at Plugin.initialise (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/Plugin.js:46:10)
    at PluginHost.load (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/PluginHost.js:54:17)
    at Plugin.load.then.loaded (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/PluginHost.js:34:63)
[info][PluginHost] [!!!] SyntaxError: Unexpected token .
    at Object.ex [as .js] (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/sandbox.js:53:19)
    at _require (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/sandbox.js:248:24)
    at module.exports.path (/Users/jme/Documents/shared/jme/code/shadowbot-core/plugins/shadowbot-plugin-spotify:3:21)
    at Object.Decontextify.object.host.Object.assign.apply.e [as apply] (/Users/jme/Documents/shared/jme/code/shadowbot-core/node_modules/vm2/lib/contextify.js:79:36)
    at e (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/Plugin.js:83:22)
    at Plugin.initialise (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/Plugin.js:46:10)
    at PluginHost.load (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/PluginHost.js:54:17)
    at Plugin.load.then.loaded (/Users/jme/Documents/shared/jme/code/shadowbot-core/src/PluginHost.js:34:63)
[info][Connection/IRC] connected and ready for messages
[info][Core] all connection handlers successfully started
```
